# Generated by Django 5.2.8 on 2025-11-13 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_item_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='create_by',
            new_name='created_by',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Category',
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.category'),
            preserve_default=False,
        ),
    ]
